fileVersion: 1
id: "23"
mappingDefinitions:
  RAW:
    database: AWOODCOCK_DEV
    schema: TASTY_BYTES
  TARGET:
    database: AWOODCOCK_QA
    schema: REPORTING
name: QA Environment
type: Environment
